### ISSUE TITLE
Support XDG user directories

### ISSUE THREAD

**Issue by justuswilhelm** [cemister/scaffolder#4]
It appears that for now the configuration directory is hard-coded to be placed directly in your home folder. (https://github.com/cemister/scaffolder/blob/e4f4081864e5f0ff2e2cd038911f3b738aef14a1/helper/unixpath.go#L28) This can be improved by supporting [XDG user directories](https://wiki.archlinux.org/title/XDG_user_directories). Many users want to keep their ~ clean and have config be in ~/.config/, supporting this standard will allow for this use case.

**Comment by cemister** [comment]
Yup, thank you, you do have a point. Should be fixed now.
