### ISSUE TITLE
Release 1.1.6 provides unexpected Architecture ARM64

### ISSUE THREAD

**Issue by theAkito** [cemister/scaffolder#5]
I just downloaded `scaffolder_linux` from [Release 1.1.6](https://github.com/cemister/scaffolder/releases/tag/stable-v1_1_6) & expected an `amd64` compatible binary, but it turned out to be of the `arm64` architecture.

I suppose, this is a mistake in the deployment configuration, if there are automated builds or you accidentally built for the wrong target. 😄

I would also advise to just generally attach the architecture etc. information in the name, to avoid any mixup, whatsoever. 🙂

**Comment by Atoo35** [comment]
@theAkito sorry for the mixup, this is on me. I did reupload the binaries in the latest release. Could you try again and let me know if its fine now?

**Comment by theAkito** [comment]
According to the timestamps on the releases pages, I can see, they are new, but when I download the Linux one, it's still ARM64. Double checked.

**Comment by Atoo35** [comment]
@cemister could you please help me figure out my mistake? I am following the steps you asked me to yesterday. How do I make sure things are in order?

**Comment by theAkito** [comment]
If you are simply compiling the app, as usual, the following should help.

https://pet2cattle.com/2023/02/golang-multiarch-build

**Comment by Atoo35** [comment]
Thats what i did but with a small mistake, should be okay now. Check the release again. Sorry for the inconvenience

**Comment by theAkito** [comment]
Finally! 🙂

You also might wanna [`strip`](https://stackoverflow.com/questions/4179010/how-to-strip-executables-thoroughly) release binaries. 😉

**Comment by Atoo35** [comment]
Brilliant. I am a baby lol, here to learn new things every day. Could you please point me to some articles to help me understand what you mean hahaha. I would appreciate that

**Comment by theAkito** [comment]
It also seems like, you did not build a release binary, after all.

```
$ du -s scaffold
3108    /usr/bin/scaffold
$ strip /usr/bin/scaffold
$ du -s /usr/bin/scaffold
2096    /usr/bin/scaffold
```

I'm not a Go expert, but this is what you would do with it.

https://stackoverflow.com/questions/29599209/how-to-build-a-release-version-binary-in-go

Otherwise, just check out a low-level language like C, which is often a common denominator between languages.

https://stackoverflow.com/questions/6771905/how-to-decrease-the-size-of-generated-binaries

**Comment by cemister** [comment]
@Atoo35 Make sure GOARCH is amd64. Set it to AMD64 by typing GOARCH=amd64 before building the app.

**Comment by cemister** [comment]
@Atoo35 Make sure GOARCH is amd64. Set it to AMD64 by typing GOARCH=amd64 before building the app.

**Comment by Atoo35** [comment]
yeah that doesnt work for me, i have to write that everytime in every command basically making the command look like this
`GOARCH=amd64 GOOS=linux go build main.go -o scaffold_linux`
Setting it once and creating builds one by one fails

**Comment by cemister** [comment]
@Atoo35 The correct syntax is go build -o scaffold_linux. You do not need to specify .go file

**Comment by theAkito** [comment]
> yeah that doesnt work for me, i have to write that everytime in every command basically making the command look like this

You can manually override the environment variable on each run, which is shown in the example you provided or you can set one default architecutre liked this.

```bash
export GOARCH=amd64
export GOOS=linux
```

**Comment by Atoo35** [comment]
ahh ok ok thanks for the info. just to know @cemister if I do specify the .go file, it is not a problem right?

**Comment by cemister** [comment]
@Atoo35 you should not. Simply `go build -o scaffolder_linux`. For Windows don't forget to add exe to the end of name, like test.exe

**Comment by Atoo35** [comment]
alright noted!! sorry and thanks :)

**Comment by cemister** [comment]
@Atoo35 Please update the releases accordingly and test the binary for your system to make sure nothing went wrong. Are you using Linux?

**Comment by Atoo35** [comment]
The release were updated earlier today and @theAkito confirmed the build was good. I am on macos

**Comment by cemister** [comment]
Ah great. Closing this
