### ISSUE TITLE
yaml variables that can set using a flag

### ISSUE THREAD

**Issue by Gwali-1** [cemister/scaffolder#6]
Hello there,
I wanted to send in a contribution cause i find this project very cool.
I  started working on the new todo as a contribution  towards the project.
Problem is  i seem to have a little confusion on what it means exactly. 
Does it mean you want a feature where users can set various variables  as key pair values using a flag eg --flags name:john, age:45 ? and where exactly is the variable supposed  to be parsed and used?
See i started working on it thinking you just wanted a way to replace file or directory names with a set yaml variable  using a flag like the example above(and i seem to have that working) but now i'm not so sure . Would be helpful if you help clarify what you mean exactly. Thanks

**Comment by cemister** [comment]
1) A variable in Yaml should be declared like this;
```$TEST: teat```
2) to use it, 
```
hello:
   hello.txt: |
        {TEST}
The variable can be set using flags, just like you said. {TEST} should be parsed to value of TEST variable

**Comment by cemister** [comment]
P.S The YAML file itself shouldn't be updated with actual variable replacing {TEST}; When you parse the YAML, you replace any reference of the variable with its corresponding variable in Go that can be allocated using `make`. Feel free to think of your own implementation though

**Comment by Gwali-1** [comment]
@cemister  i made some code modifications following your first reply and now all references  of a variable are  replaced with its corresponding value in the generated output not the yaml file containing the scaffold.  i should send a PR in any minute .

eg setting some variables by flag like this --values name:john, age:44
hello:
      hello.go: |
            fmt.Println("{name}")

output => fmt.Println("john")

**Comment by cemister** [comment]
Great! You may as well update the README and then I'll merge.

**Comment by Gwali-1** [comment]
sure thing!
